// OpenAPI 3.0 (resumido) — descreve os principais endpoints das microarquiteturas.
const P = (summary: string, tag: string, auth = true) => ({
  summary, tags: [tag], ...(auth ? { security: [{ bearerAuth: [] }] } : {}),
  responses: { '200': { description: 'OK' } },
});

export const openapiDoc = {
  openapi: '3.0.3',
  info: { title: 'Sistema de Gestão Documental de Campanha', version: '1.0.0', description: 'API v2 — 35 microarquiteturas com adapters de produção (Anthropic, Twilio, Resend, ClickSign).' },
  servers: [{ url: '/' }],
  components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } },
  paths: {
    '/api/health': { get: P('Health check', 'plataforma', false) },
    '/api/ready': { get: P('Readiness (banco)', 'plataforma', false) },
    '/api/login': { post: P('Autenticação (JWT)', 'identidade', false) },
    '/api/me': { get: P('Perfil do usuário', 'identidade') },
    '/api/candidatos': { get: P('Lista candidatos no escopo', 'hierarquia') },
    '/api/dashboard': { get: P('Painel agregado', 'dashboards') },
    '/api/documentos': { get: P('Lista documentos', 'documentos') },
    '/api/documentos/gerar': { post: P('Gera contrato', 'documentos') },
    '/api/documentos/{id}/timeline': { get: P('Linha do tempo do documento', 'auditoria') },
    '/api/documentos/{id}/assinar-admin': { post: P('Assinatura do administrador', 'assinatura') },
    '/api/documentos/{id}/reemitir': { post: P('Reemissão', 'reemissao') },
    '/api/documentos/{id}/contestar': { post: P('Contestação', 'contestacao') },
    '/api/assinatura/assistida/iniciar': { post: P('Inicia assinatura assistida', 'assinatura') },
    '/api/assinatura/assistida/assinar': { post: P('Conclui assinatura assistida', 'assinatura') },
    '/api/assinatura/remota/criar': { post: P('Cria link de assinatura remota', 'assinatura') },
    '/api/publico/assinatura/remota/otp': { post: P('OTP da assinatura remota (mock)', 'assinatura', false) },
    '/api/publico/assinatura/remota/concluir': { post: P('Conclui assinatura remota', 'assinatura', false) },
    '/api/importacao/previa': { post: P('Prévia de importação em massa', 'importacao') },
    '/api/importacao/{batchId}/confirmar': { post: P('Confirma importação (idempotente)', 'importacao') },
    '/api/notificacoes/enviar': { post: P('Envia notificação (idempotente)', 'notificacoes') },
    '/api/papel/solicitar': { post: P('Solicita exceção em papel (QR)', 'papel') },
    '/api/papel/{caseId}/escanear': { post: P('Escaneia/valida QR (OCR mock)', 'papel') },
    '/api/papel/{caseId}/revisar': { post: P('Revisa exceção em papel', 'papel') },
    '/api/offline/pacote': { post: P('Gera pacote offline cifrado', 'offline') },
    '/api/offline/sync': { post: P('Sincroniza pacote (rejeita expirado)', 'offline') },
    '/api/antifraude/avaliar': { post: P('Avalia risco', 'antifraude') },
    '/api/antifraude/casos': { get: P('Lista sinais e casos de fraude', 'antifraude') },
    '/api/ocr/processar': { post: P('Processa OCR (mock) e detecta divergência', 'ia-ocr') },
    '/api/lgpd/solicitacao': { post: P('Solicitação do titular (LGPD)', 'lgpd') },
    '/api/lgpd/legal-hold': { post: P('Ativa legal hold', 'lgpd') },
    '/api/lgpd/descarte': { post: P('Descarte (bloqueado por legal hold)', 'lgpd') },
    '/api/suporte/acesso/solicitar': { post: P('Solicita acesso de suporte', 'suporte') },
    '/api/suporte/acesso/{reqId}/aprovar': { post: P('Aprova acesso de suporte', 'suporte') },
    '/api/suporte/acesso/{reqId}/dados': { get: P('Dados mascarados (com aprovação)', 'suporte') },
    '/api/incidentes': { post: P('Abre incidente', 'incidente') },
    '/api/auditoria/{candidateId}/verificar': { get: P('Verifica cadeia de custódia', 'auditoria') },
    '/api/auditoria-externa/{candidateId}/pacote': { post: P('Gera pacote de auditoria externa', 'auditoria-externa') },
    '/api/exportacao/candidato/{candidateId}': { post: P('Exporta dossiê contábil', 'exportacao') },
    '/api/exportacao/{id}/download': { get: P('Baixa dossiê (ZIP)', 'exportacao') },
    '/api/observabilidade/metricas': { get: P('Métricas', 'observabilidade') },
    '/api/backup/executar': { post: P('Registra backup + restore test', 'backup') },
    '/api/connectors/status': { get: P('Status das integrações (Anthropic/Twilio/Resend/ClickSign)', 'plataforma') },
    '/api/assinatura/eletronica/enviar': { post: P('Cria envelope de assinatura externa (ClickSign/D4Sign)', 'assinatura-externa') },
    '/api/assinatura/eletronica/webhook/{provider}': { post: P('Webhook do provedor de assinatura externa', 'assinatura-externa', false) },
  },
};
